import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter_Tight, DM_Sans, Plus_Jakarta_Sans } from 'next/font/google'
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "./components/Navbar";

const dmSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: "--font-dm_sans",
});

const inter = Inter_Tight({
  subsets: ['latin'],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} ${dmSans.variable} antialiased text-black bg-[#00000] dark:text-white dark:bg-[#0b0b0b]`}
      >
        <Providers>
          <Navbar></Navbar>
          {children}
        </Providers>
      </body>
    </html>
  );
}
